# -*- coding: utf-8 -*-
"""food_delivery_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frCJ3PkJBdC1I8eQV2KFhg7EsPmV49Wd
"""

import pandas as pd
import sqlite3
from google.colab import drive

drive.mount('/content/drive')
base_path="/content/drive/MyDrive/"

import os
os.listdir("/content/drive/MyDrive")

orders=pd.read_csv(base_path+"orders.csv")
users=pd.read_json(base_path+"users.json")

conn=sqlite3.connect(":memory:")
with open(base_path + "restaurants.sql") as f:
  conn.executescript(f.read())
restaurant=pd.read_sql_query("SELECT * FROM restaurants",conn)

final=orders.merge(users,on='user_id',how='left') \
.merge(restaurant,how="left")

final.head()

final.shape

final.to_csv(base_path+"final_food_delivery_dateset.csv",index=False)

len(final)
final["total_amount"].sum()
final[final["membership"]=="Gold"].shape[0]
final.groupby("city")["total_amount"].sum()